FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD backagainmaven.jar /opt/backagainmaven/
EXPOSE 8080
WORKDIR /opt/backagainmaven/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "backagainmaven.jar"]
